name: Node.js CI

on:
  push:
    branches: [main, master, next, patch]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["lts/*"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        run: mv .env.example .env

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: true

      - name: Build project
        run: npm run generate

      - name: Push to S3
        run: |
          aws s3 sync dist/ s3://${{ env.AWS_S3_BUCKET }}/api-editor/
          aws cloudfront create-invalidation --distribution-id ${{secrets.AWS_LANDING_CLOUDFRONT_ID_TEST}} --paths "/*"
