name: Node.js CI

on:
  push:
    branches: [test]

env:
  AWS_REGION: eu-west-1
  AWS_S3_BUCKET: tf-loadiumio

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["lts/*"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        run: mv .env.example .env

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build project
        run: npm run generate

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_TEST }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_TEST }}
          aws-region: ${{ env.AWS_REGION }}


      - name: Push to S3
        run: |
          aws s3 sync packages/hoppscotch-selfhost-web/dist s3://${{ env.AWS_S3_BUCKET }}/api-editor/
          aws cloudfront create-invalidation --distribution-id ${{secrets.AWS_LANDING_CLOUDFRONT_ID_TEST}} --paths "/*"
